feat(vmresourcetags): enabling virtualmachineresourcetags usage
stone-payments/ansible-role-vsts-agent pull request #17
Opened 2022-02-14 23:22 UTC by leandrolpereira

## Description

This PR enables "virtualmachinesresourcetags" usage during vsts agent installation.

## Motivation and Context

We can use a single environment for different deployments stages using virtual machine resource tags.

## How Has This Been Tested?

We tested this new feature in one of deploys.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-02-15 14:39 UTC, endersonmenezes requested changes
Poxa, não seria mais interessante colocar a variável nos defaults? Essa validação não é das mais bonitas. 
E outra, o que acha de tentar colocar essa task para rodar nas duas famílias RHEL e DEBIAN?

2022-02-15 15:17 UTC, phsmithcc approved these changes

2022-02-15 17:56 UTC, renatocmaia approved these changes

2022-02-15 17:56 UTC, endersonmenezes approved these changes

2022-02-16 14:39 UTC, marcusteixeira approved these changes

2022-02-16 14:41 UTC, merged