Fixing error when applying to new virtual machine
stone-payments/ansible-role-vsts-agent pull request #3
Opened 2021-07-12 21:20 UTC by cidico

- For the newly created virtual machines running CentOS we need to clear the expired cache and install the **epel** package;

- Fixing the package installation during the installation process;

2021-07-12 21:21 UTC, LuanFMelo approved these changes

2021-07-12 21:35 UTC, cnatan requested changes

2021-07-12 21:35 UTC, cnatan commented on tasks/rhel/install_vsts_agent.yml
> +  command: "yum -y install {{item}}"
Why change from module `yum` to raw command?

2021-07-12 21:35 UTC, cnatan commented on tasks/rhel/install_vsts_agent.yml
> +- name: Clean the expired cache
The expired cache clean-up is needed before and after the epel install?

2021-07-12 21:35 UTC, cnatan commented on tasks/rhel/install_vsts_agent.yml
> +- name: Install epel
Why not use the package module?

2021-07-12 21:35 UTC, cnatan commented on tasks/rhel/install_vsts_agent.yml
> -    - pkg
Why remove the task tag?

2021-07-13 01:43 UTC, daianmartinho commented
@cidico could you test this changes? https://github.com/stone-payments/ansible-role-vsts-agent/pull/5

2021-07-22 15:17 UTC, LuanFMelo commented
Can we close this PR ? @cidico

2021-07-26 20:09 UTC, closed without merging